title: "Ndapa Nakashole"
description: "Personal site of Ndapa Nakashole | Ndapandula"
url: "https://ndapa.us"
baseurl: "" # keep this empty for user site

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name: Ndapa Nakashole
