title: "Ndapa Nakashole"
description: "Personal site of Ndapa"
url: "https://ndapa.github.io"
baseurl: "" # keep this empty for user site

theme: minima
plugins:
  - jekyll-feed

author:
  name: Ndapa Nakashole
